### ISSUE TITLE
新八本5.4，视图输出json的BUG

### ISSUE THREAD

**Issue by ziqiming** [poetbi/boaphp#1]
输出数组结果是对象
![8M11 AF}CX(6ZX8NB_0 HMG](https://github.com/poetbi/boaphp/assets/19550939/693b7a45-7248-4d12-9a5e-d12b35484ba3)

退回5.2测试是正常的
![LL @GI9SW(0`M24S}94R93A](https://github.com/poetbi/boaphp/assets/19550939/801b4ad0-57f9-45fc-931e-76d5f2740fc0)

**Comment by poetbi** [comment]
已更新
