### ISSUE TITLE
关于JSON的输出配置

### ISSUE THREAD

**Issue by ziqiming** [poetbi/boaphp#2]
![image](https://github.com/poetbi/boaphp/assets/19550939/06140f74-cee0-4af1-9e13-563321ae2cd9)

msg:"<i>名称</i>只能包含字母和数字；<br>@"

data已经说明了报错的字段名，msg怎么设置让他精确的说明错误内容呢，不要带<i></i>乱七八糟的标点符号

**Comment by ziqiming** [comment]
这个是自动验证器来的

**Comment by poetbi** [comment]
那是错误调试信息，帮助定位错误的，配置中关闭DEBUG就没有了（手册里也有说明）。

'DEBUG' => false 或删除 DEBUG 配置

**Comment by ziqiming** [comment]
我就是关闭了也提示这个，，，不关闭附带错误更多，包含的错误代码和路径等信息

**Comment by poetbi** [comment]
修改/boa/msg.php，最后一个方法：

	private static function format_log($log, $br = '<br>'){
		if($log){
			if(is_array($log)){
				$str = $br .'@'. implode($br .'@', $log);
			}else{
				$str = $br .'@'. $log;
			}
			return $str;
		}
	}

添加 if($log) 判断，我稍后更新

**Comment by ziqiming** [comment]
这段代码没有解决，判断$log不行吧，$log已经是array了
是不是count($log)?

不懂解构，还是下次老大更新下吧。

**Comment by poetbi** [comment]
没事，你就用这个覆盖之前的 format_log() 方法就行，数组和字符串都可以这么判断，我更新也是这样的，暂时还没发布

**Comment by ziqiming** [comment]
覆盖了无效呀

**Comment by ziqiming** [comment]
![image](https://github.com/poetbi/boaphp/assets/19550939/c876c141-e4d3-4eac-95a1-8632707f45df)

**Comment by poetbi** [comment]
已更新
