### ISSUE TITLE
关于数据库配置参数的缺省值问题

### ISSUE THREAD

**Issue by ziqiming** [poetbi/boaphp#4]
我是个新手，我设置了

'DATABASE' => [
		'host' => '127.0.0.1' ,
		'user' => 'root' ,
		'pass' => '123456' , 
		'name' => 'shop'
]

居然错误的配置，，

必须要带上两个参数

'DATABASE' => [
		'host' => '192.168.31.251' ,
		'user' => 'root' ,
		'pass' => '123456' , 
		'name' => 'shop',
		'prefix' => '',
		'charset' => 'utf8',
],

配上'prefix' => '', 'charset' => 'utf8' 才正常

这个应该做到第一种配置就能用才好吧。

**Comment by poetbi** [comment]
那个不是必须配置的，'prefix'有个默认值'bs_'，如果数据表没有前缀的话，则需要配置为空

**Comment by poetbi** [comment]
下次更新时可以取消默认值
