### ISSUE TITLE
关于上传upload方法

### ISSUE THREAD

**Issue by ziqiming** [poetbi/boaphp#5]
默认上传路径为 

BS_WWW .'file/'

上传后根据年/月/日来生成文件夹并保存到目录中

1、提交过来的图片是jpg格式，为什么保存后的后缀名是PNG呢？应该是上传文件是jpg就附带jpg，是zip就附带zip的后缀名
2、自定义名字后，文件居然保存到 BS_WWW .'file/'  根目录了，没有年月日的文件夹了，既然没有配置生成目录就应该依照默认生成路径规则呀
3、自定义名字后，文件的后缀名丢失，这里应该自定义的是文件名名称，后缀名还要调用处理就太麻烦了，。

**Comment by ziqiming** [comment]
上传多图片，两个参数名，分别是两张，一个请求过来了。请问这种图片怎么接收

![image](https://github.com/poetbi/boaphp/assets/19550939/3fb39214-4559-46c6-ad66-c5352cba0ac7)

PS:算了，本来在前端裁剪一张缩略图过来保存起来，有点门槛，还是后端生成缩略图吧。还要改逻辑

**Comment by ziqiming** [comment]
![image](https://github.com/poetbi/boaphp/assets/19550939/85a95e68-94c7-4be1-942a-9e5e1fb3c62b)

**Comment by ziqiming** [comment]
![image](https://github.com/poetbi/boaphp/assets/19550939/c301cb64-8fec-440f-943d-c64946cd1b4d)

![image](https://github.com/poetbi/boaphp/assets/19550939/0e9ccc21-b553-4bc8-a72e-526d77fef106)

**Comment by ziqiming** [comment]
现在的问题是，需要给上传文件设定一个名字。。
one的参数里面有设置名字，但是不带后缀名，在one函数之前没有后缀名信息啊

$id   = id();
$up   = boa::upload();
$name = $up->cfg('path') . 'image/' . $id . **$file['exts']**;
$res  = $up->one('fileVal'， **$name**);
$file = $up->get_file();

**Comment by ziqiming** [comment]
现在的问题是，需要给上传文件设定一个名字。。
one的参数里面有设置名字，但是不带后缀名，在one函数之前没有后缀名信息啊

$id   = id();
$up   = boa::upload();
$name = $up->cfg('path') . 'image/' . $id . **$file['exts']**;
$res  = $up->one('fileVal'， **$name**);
$file = $up->get_file();

**Comment by ziqiming** [comment]
现在的问题是，需要给上传文件设定一个名字。。
one的参数里面有设置名字，但是不带后缀名，在one函数之前没有后缀名信息啊

$id   = id();
$up   = boa::upload();
$name = $up->cfg('path') . 'image/' . $id . **$file['exts']**;
$res  = $up->one('fileVal'， **$name**);
$file = $up->get_file();

**Comment by ziqiming** [comment]
![image](https://github.com/poetbi/boaphp/assets/19550939/8a17e924-b1b5-4f50-bb04-2010629d0f9e)

**Comment by ziqiming** [comment]
PHP环境限制了默认2M，我在程序设置$up->cfg('size' , 10) ;

超过限定大小时没有错误提示吗？

**Comment by poetbi** [comment]
【1】.上传目录中没有文件
这个可能是报错了，刚更新了程序，完善了错误提示，请更新；

【2】.同时上传多个文件，有2种方法：
$up = boa::upload();

第一种，不同字段名
$up->one('min');
$min = $up->get_file();
$up->one('fileVal');
$val= $up->get_file();

第二种，相同字段名，比如：file[]
$up->more('file');
$arr= $up->get_files();

【3】.文件上传后后缀不符
这个我多次测试没有发现问题，我猜测可能是你的电脑隐藏了真实的文件后缀，比如：1.png.jpg，在你的电脑上显示为1.png，实际是jpg文件，解决办法如下（根据你电脑选择合适的）
https://www.baidu.com/s?ie=utf-8&wd=windows显示文件后缀

**Comment by ziqiming** [comment]
确实是我的测试图片问题。。感谢老大更新~！
