### ISSUE TITLE
$this->request的使用问题

### ISSUE THREAD

**Issue by ziqiming** [poetbi/boaphp#6]
之前 $this->user 被占用了验证

后面传递了一个user的参数

我使用$this->request->v('user') 来接收，结果还是$this->user的信息呢

我使用
$this->request = boa::request();
echo $this->request->v('user');

仍然还是$this->user的数据      这里应该怎么用呢，是我理解的不对吗？

**Comment by poetbi** [comment]
$this->user 完全等同于$this->request->v('user')，采用后者写法是因为控制器类中具有$user属性了（一般情况下不会发生）

没有明白“被占用验证，后面传递了参数”，可以贴上具体代码
一般在同一页面中，user会按照一定顺序取值（参见手册/验证/请求变量）

除非必要可以使用不同参数名

**Comment by ziqiming** [comment]
![image](https://github.com/poetbi/boaphp/assets/19550939/1677c7cb-ca12-401b-8662-c2208d7906c7)

**Comment by poetbi** [comment]
__construct()中$this->user属于控制器的一个属性了，不是请求变量，除非后面方法中用到这个属性，否则为什么要创建这么多控制器属性，从性能上讲也不好
	$user = ...
	if(!$user['id']){...}
使用局部变量不会与后面产生冲突，局部用完即时销毁，性能上也较优。



按照你目前的写法，del()可以有如下解决办法：
1.如果想删除当前用户的
	'id' => $this->user['id'],
2.如果想删除传入用户user，注意：此处不能使用$this->user获取参数了，与类user属性同名
	'id' => $this->request->v('user'),
3.其实也可以换个传入参数，如：uid
	'id' => $this->uid,

**Comment by ziqiming** [comment]
能不能优先级  ，默认可以接受$this->user参数  但是如果我单独使用 $this->request->v('user')  就一定从提交过来的参数中获取？

这样干扰了接受参数和定义的变量，区分有点混乱啊

我这个声明私有变量的写法不是PHP标准写法吗？
![image](https://github.com/poetbi/boaphp/assets/19550939/a6ec0a82-d99b-444f-95e3-c4d6f9999fc3)

$this->user这个是登录的用户身份，每个页面都有一个，下面每个方法都可以用啊

**Comment by ziqiming** [comment]
$this->user 是个对象包含登录者的信息，名字ID权限等等

要删除的这个是会员ID   不是一个表的

**Comment by ziqiming** [comment]
现在我使用  $this->request->v('user')  接受也被$this->user 覆盖了，$this->request->v('user') 得到的数据是$this->user的

**Comment by poetbi** [comment]
你C语言中文网的例子__construct()中的$this->name在后面demo()中用到了，
__construct()中变量如果后面用不到，没必要全部加$this，容易冲突还浪费性能

标准写法是在头部像$table一样申明一个 private $user;
按照你的想法，那del()中就用： $this->request->v('user') 
参数名只是一个符号，abc  user1  usr  users等等

**Comment by ziqiming** [comment]
哦。我再试试

**Comment by ziqiming** [comment]
![Uploading image.png…]()

OK。还是我的问题。。。
