### ISSUE TITLE
有没有视频处理的相关方法？

### ISSUE THREAD

**Issue by ziqiming** [poetbi/boaphp#7]
比如我上传了一个MP4，需要PHP来进行转码？读取文件的缩略图。

**Comment by poetbi** [comment]
boaPHP暂无视频处理。

这个可以用PHP+FFmpeg实现（网上教程很多），可以自行实现个video类，用boa::video()访问，boaPHP的结构统一简单，非常易于扩展。

**Comment by ziqiming** [comment]
好，没有问题
